/**
 * What to point the student at for each step (the "next objective" marker, like a waypoint):
 * `practical:step` -> interactive id. Steps done on paper or in a panel have no marker.
 */
export const STEP_TARGET: Record<string, string> = {
  'titration:fill': 'chem_naoh_bottle',
  'titration:funnel': 'chem_funnel',
  'titration:jet': 'chem_stopcock',
  'titration:pipette': 'chem_pipette',
  'titration:indicator': 'chem_dropper',
  'titration:initial': 'chem_burette',
  'titration:titrate': 'chem_stopcock',
  'titration:final': 'chem_burette',
  'titration:repeat': 'chem_flask',
  'titration:handin': 'chem_clipboard',
  'microscopy:low': 'micro_turret',
  'microscopy:focus4': 'micro_coarse_focus',
  'microscopy:focus10': 'micro_turret',
  'microscopy:focus40': 'micro_fine_focus',
  'microscopy:capture': 'micro_eyepieces',
  'ohms-law:wire': 'phys_return_lead',
  'ohms-law:close': 'phys_knife_switch',
  'ohms-law:measure': 'phys_potentiometer',
  'ohms-law:open': 'phys_knife_switch',
  'weighing:tare': 'res_tare_btn',
  'weighing:open': 'res_balance_door',
  'weighing:add': 'spatula',
  'weighing:close': 'res_balance_door',
  'flame:sash': 'hood_sash',
  'flame:light': 'flame_gas_tap',
  'flame:blue': 'flame_air_collar',
  'flame:tests': 'flame_loop',
  'flame:off': 'flame_gas_tap',
  'pendulum:release': 'pend_bob',
  'pendulum:time': 'pend_watch',
  'pendulum:lengths': 'pend_clamp',
  'rates:mix': 'rates_thio_30',
  'rates:react': 'rates_acid',
  'rates:time': 'rates_watch',
  'rates:repeat': 'rates_flask',
  'osmosis:setup': 'osm_strips',
  'osmosis:reweigh': 'osm_tube_0',
  'chroma:baseline': 'chroma_pencil',
  'chroma:spots': 'chroma_inks',
  'chroma:run': 'chroma_paper',
  'chroma:remove': 'chroma_paper',
};
